package gui.view;

import gui.controller.Controlador_Configuracio;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 * Pantalla Configuració que permet modificar els valors de les Mascotes i Menjadores
 * @author Oriol Coll Salvia
 */
public class Pantalla_Configuracio extends javax.swing.JFrame {

    private Controlador_Configuracio confControl = new Controlador_Configuracio();
    
    /**
     * Construeix la Pantalla Configuració i n'inicia els components
     */
    public Pantalla_Configuracio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        nomMascotaEsquerra = new javax.swing.JTextField();
        pesMascotaEsquerra = new javax.swing.JTextField();
        limitDiariEsquerraText = new javax.swing.JTextField();
        raccionsDiariesEquerraText = new javax.swing.JTextField();
        raccioExtraText = new javax.swing.JTextField();
        alertaDipositDretaText = new javax.swing.JTextField();
        alertaDipositEsquerraText = new javax.swing.JTextField();
        nomMascotaDreta = new javax.swing.JTextField();
        pesMascotaDreta = new javax.swing.JTextField();
        edatMascotaDreta = new javax.swing.JTextField();
        limitDiariDretaText = new javax.swing.JTextField();
        edatMascotaEsquerra = new javax.swing.JTextField();
        raccionsDiariesDretaText = new javax.swing.JTextField();
        gatGosDreta = new javax.swing.JComboBox<>();
        gatGosEsquerra = new javax.swing.JComboBox<>();
        botoSortir = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        botoValidar = new javax.swing.JButton();
        limitNivellDipositBuitLabel = new javax.swing.JLabel();
        fonsPantallaConfiguracio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuració Menjadores");
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("*******");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 102));
        jLabel16.setText("Raccions diàries");
        jLabel16.setToolTipText("");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 30));

        jLabel17.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 51, 255));
        jLabel17.setText("Edat");
        jLabel17.setToolTipText("");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel19.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 51, 255));
        jLabel19.setText("Tipus mascota");
        jLabel19.setToolTipText("");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel20.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 51, 255));
        jLabel20.setText("Mascota Esquerra");
        jLabel20.setToolTipText("");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel9.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 255));
        jLabel9.setText("Pes");
        jLabel9.setToolTipText("");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        jLabel10.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 255));
        jLabel10.setText("kg");
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 40));

        jLabel11.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 51, 255));
        jLabel11.setText("anys");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, 50));

        jLabel23.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 102));
        jLabel23.setText("Limít Diari");
        jLabel23.setToolTipText("");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel21.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 102));
        jLabel21.setText("Mascota Dreta");
        jLabel21.setToolTipText("");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        jLabel22.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 0, 102));
        jLabel22.setText("Tipus mascota");
        jLabel22.setToolTipText("");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 102));
        jLabel12.setText("Pes");
        jLabel12.setToolTipText("");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 30));

        jLabel24.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 102));
        jLabel24.setText("Edat");
        jLabel24.setToolTipText("");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel25.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 102));
        jLabel25.setText("Límit Diari");
        jLabel25.setToolTipText("");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel13.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 102));
        jLabel13.setText("kg");
        jLabel13.setToolTipText("");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, 40));

        jLabel27.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 0, 102));
        jLabel27.setText("anys");
        jLabel27.setToolTipText("");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, 50));

        jLabel8.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8.setText("grams");
        jLabel8.setToolTipText("");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, 30));

        jLabel28.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 102));
        jLabel28.setText("grams");
        jLabel28.setToolTipText("");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, 50));

        jLabel30.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 153, 102));
        jLabel30.setText("Raccions diàries");
        jLabel30.setToolTipText("");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 30));

        jLabel29.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 153, 102));
        jLabel29.setText("grams");
        jLabel29.setToolTipText("");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, 50));

        jLabel31.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 102));
        jLabel31.setText("Nivell alerta dipòsits (cm)");
        jLabel31.setToolTipText("");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        nomMascotaEsquerra.setBackground(new java.awt.Color(204, 204, 204));
        nomMascotaEsquerra.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        nomMascotaEsquerra.setForeground(new java.awt.Color(0, 0, 0));
        nomMascotaEsquerra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomMascotaEsquerra.setText("BONNIE");
        nomMascotaEsquerra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255), 2));
        nomMascotaEsquerra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomMascotaEsquerraFocusLost(evt);
            }
        });
        jPanel2.add(nomMascotaEsquerra, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 20, 160, 30));

        pesMascotaEsquerra.setBackground(new java.awt.Color(204, 204, 204));
        pesMascotaEsquerra.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        pesMascotaEsquerra.setForeground(new java.awt.Color(0, 0, 0));
        pesMascotaEsquerra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pesMascotaEsquerra.setText("4");
        pesMascotaEsquerra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255), 2));
        pesMascotaEsquerra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesMascotaEsquerraFocusLost(evt);
            }
        });
        jPanel2.add(pesMascotaEsquerra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 50, 30));

        limitDiariEsquerraText.setBackground(new java.awt.Color(204, 204, 204));
        limitDiariEsquerraText.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        limitDiariEsquerraText.setForeground(new java.awt.Color(0, 0, 0));
        limitDiariEsquerraText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        limitDiariEsquerraText.setText("160");
        limitDiariEsquerraText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        jPanel2.add(limitDiariEsquerraText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 60, 30));

        raccionsDiariesEquerraText.setBackground(new java.awt.Color(204, 204, 204));
        raccionsDiariesEquerraText.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        raccionsDiariesEquerraText.setForeground(new java.awt.Color(0, 0, 0));
        raccionsDiariesEquerraText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        raccionsDiariesEquerraText.setText("9");
        raccionsDiariesEquerraText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        jPanel2.add(raccionsDiariesEquerraText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 60, 30));

        raccioExtraText.setBackground(new java.awt.Color(204, 204, 204));
        raccioExtraText.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        raccioExtraText.setForeground(new java.awt.Color(0, 0, 0));
        raccioExtraText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        raccioExtraText.setText("5");
        raccioExtraText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        jPanel2.add(raccioExtraText, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 50, 30));

        alertaDipositDretaText.setBackground(new java.awt.Color(204, 204, 204));
        alertaDipositDretaText.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        alertaDipositDretaText.setForeground(new java.awt.Color(0, 0, 0));
        alertaDipositDretaText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alertaDipositDretaText.setText("20");
        alertaDipositDretaText.setToolTipText("Límit d'alerta per a nivell de dipòsit baix");
        alertaDipositDretaText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102), new java.awt.Color(204, 0, 102), new java.awt.Color(204, 0, 102)));
        jPanel2.add(alertaDipositDretaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 50, -1));

        alertaDipositEsquerraText.setBackground(new java.awt.Color(204, 204, 204));
        alertaDipositEsquerraText.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        alertaDipositEsquerraText.setForeground(new java.awt.Color(0, 0, 0));
        alertaDipositEsquerraText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alertaDipositEsquerraText.setText("20");
        alertaDipositEsquerraText.setToolTipText("Límit d'alerta per a nivell de dipòsit baix");
        alertaDipositEsquerraText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102), new java.awt.Color(153, 51, 255), new java.awt.Color(153, 51, 255)));
        jPanel2.add(alertaDipositEsquerraText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 50, -1));

        nomMascotaDreta.setBackground(new java.awt.Color(204, 204, 204));
        nomMascotaDreta.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        nomMascotaDreta.setForeground(new java.awt.Color(0, 0, 0));
        nomMascotaDreta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomMascotaDreta.setText("nom Mascota");
        nomMascotaDreta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 2));
        nomMascotaDreta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomMascotaDretaFocusLost(evt);
            }
        });
        jPanel2.add(nomMascotaDreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 160, 30));

        pesMascotaDreta.setBackground(new java.awt.Color(204, 204, 204));
        pesMascotaDreta.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        pesMascotaDreta.setForeground(new java.awt.Color(0, 0, 0));
        pesMascotaDreta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pesMascotaDreta.setText("4");
        pesMascotaDreta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 2));
        pesMascotaDreta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesMascotaDretaFocusLost(evt);
            }
        });
        jPanel2.add(pesMascotaDreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 50, 30));

        edatMascotaDreta.setBackground(new java.awt.Color(204, 204, 204));
        edatMascotaDreta.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        edatMascotaDreta.setForeground(new java.awt.Color(0, 0, 0));
        edatMascotaDreta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edatMascotaDreta.setText("2");
        edatMascotaDreta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 2));
        edatMascotaDreta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edatMascotaDretaFocusLost(evt);
            }
        });
        jPanel2.add(edatMascotaDreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 50, 30));

        limitDiariDretaText.setBackground(new java.awt.Color(204, 204, 204));
        limitDiariDretaText.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        limitDiariDretaText.setForeground(new java.awt.Color(0, 0, 0));
        limitDiariDretaText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        limitDiariDretaText.setText("160");
        limitDiariDretaText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        jPanel2.add(limitDiariDretaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 60, 30));

        edatMascotaEsquerra.setBackground(new java.awt.Color(204, 204, 204));
        edatMascotaEsquerra.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        edatMascotaEsquerra.setForeground(new java.awt.Color(0, 0, 0));
        edatMascotaEsquerra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edatMascotaEsquerra.setText("2");
        edatMascotaEsquerra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255), 2));
        edatMascotaEsquerra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edatMascotaEsquerraFocusLost(evt);
            }
        });
        jPanel2.add(edatMascotaEsquerra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 50, 30));

        raccionsDiariesDretaText.setBackground(new java.awt.Color(204, 204, 204));
        raccionsDiariesDretaText.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        raccionsDiariesDretaText.setForeground(new java.awt.Color(0, 0, 0));
        raccionsDiariesDretaText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        raccionsDiariesDretaText.setText("9");
        raccionsDiariesDretaText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        jPanel2.add(raccionsDiariesDretaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 60, 30));

        gatGosDreta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gat", "Gos", " " }));
        gatGosDreta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gatGosDretaFocusLost(evt);
            }
        });
        jPanel2.add(gatGosDreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 110, -1));

        gatGosEsquerra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gat", "Gos", " " }));
        gatGosEsquerra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gatGosEsquerraFocusLost(evt);
            }
        });
        jPanel2.add(gatGosEsquerra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 110, -1));

        botoSortir.setForeground(new java.awt.Color(0, 0, 0));
        botoSortir.setText("ACTUALITZA MASCOTES");
        botoSortir.setToolTipText("Actualitza nom, tipus, pes i edat");
        botoSortir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 51, 255), new java.awt.Color(153, 51, 255), new java.awt.Color(204, 0, 102), new java.awt.Color(204, 0, 102)));
        botoSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoSortirActionPerformed(evt);
            }
        });
        jPanel2.add(botoSortir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 180, 60));

        jLabel15.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 255));
        jLabel15.setText("Contrassenya");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        jLabel18.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 255));
        jLabel18.setText("usuari1");
        jLabel18.setToolTipText("");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 60, -1, -1));

        jLabel32.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 153, 102));
        jLabel32.setText("Raccio Extra");
        jLabel32.setToolTipText("");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 62, -1, 30));

        jLabel33.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 255));
        jLabel33.setText("1");
        jLabel33.setToolTipText("");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, -1, -1));

        jLabel34.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 255));
        jLabel34.setText("MAQUINA ID");
        jLabel34.setToolTipText("");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jLabel36.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 255));
        jLabel36.setText("USUARI");
        jLabel36.setToolTipText("");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        botoValidar.setForeground(new java.awt.Color(0, 0, 0));
        botoValidar.setText("ACTUALITZA LÍMITS");
        botoValidar.setToolTipText("Actualitza limits diaris, raccions, raccio exra i nivells dipòsit");
        botoValidar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 5));
        botoValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoValidarActionPerformed(evt);
            }
        });
        jPanel2.add(botoValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 160, 60));

        limitNivellDipositBuitLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        limitNivellDipositBuitLabel.setForeground(new java.awt.Color(255, 4, 12));
        limitNivellDipositBuitLabel.setText("10 cm.");
        limitNivellDipositBuitLabel.setToolTipText("Nivell restant de pinso en que es blocarà el motor fins que no es torni a omplir el dipòsit. Prémer RACCIÓ EXTRA per forçar el motor ");
        limitNivellDipositBuitLabel.setName(""); // NOI18N
        jPanel2.add(limitNivellDipositBuitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 330, 60, 60));

        fonsPantallaConfiguracio.setIcon(new javax.swing.ImageIcon("C:\\Users\\oriol\\OneDrive\\Documents\\NetBeansProjects\\Servidor_Menjadora-master\\src\\main\\java\\gui\\view\\images\\Ensamblatge54projecte.JPG")); // NOI18N
        fonsPantallaConfiguracio.setText("jLabel2");
        fonsPantallaConfiguracio.setMaximumSize(new java.awt.Dimension(541, 165));
        jPanel2.add(fonsPantallaConfiguracio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoSortirActionPerformed
        // TODO add your handling code here:
        confControl.editaMascota();       
        dispose();
    }//GEN-LAST:event_botoSortirActionPerformed

    private void nomMascotaEsquerraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomMascotaEsquerraFocusLost
        // TODO add your handling code here:
        String nomEsquerra = nomMascotaEsquerra.getText();
        confControl.getMascotaEsquerra().setNom(nomEsquerra);
    }//GEN-LAST:event_nomMascotaEsquerraFocusLost

    private void nomMascotaDretaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomMascotaDretaFocusLost
        // TODO add your handling code here:
        String nomDreta = nomMascotaDreta.getText();
        confControl.getMascotaDreta().setNom(nomDreta);
    }//GEN-LAST:event_nomMascotaDretaFocusLost

    private void pesMascotaEsquerraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesMascotaEsquerraFocusLost
        // TODO add your handling code here:
        try{
            double pes = Double.parseDouble(pesMascotaEsquerra.getText());
            confControl.getMascotaEsquerra().setPesMascota(pes);
        }catch(NumberFormatException ex){
            System.err.println("\t\t\t ERROR!! Pes Mascota Esquerra invàlid !!!!");
        }
    }//GEN-LAST:event_pesMascotaEsquerraFocusLost

    private void pesMascotaDretaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesMascotaDretaFocusLost
        // TODO add your handling code here:
        try{
            confControl.getMascotaDreta().setPesMascota(Double.parseDouble(pesMascotaDreta.getText()));
        }catch(NumberFormatException ex){
            System.err.println("\t\t\t ERROR!! Pes Mascota Dreta invàlid !!!!");
        }
    }//GEN-LAST:event_pesMascotaDretaFocusLost

    private void edatMascotaEsquerraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edatMascotaEsquerraFocusLost
        // TODO add your handling code here:
        try{
            confControl.getMascotaEsquerra().setEdat(Integer.valueOf(edatMascotaEsquerra.getText()));
        }catch(NumberFormatException ex){
            System.err.println("\t\t\t ERROR!! Edat Mascota Esquerra invàlid !!!!");
        }
    }//GEN-LAST:event_edatMascotaEsquerraFocusLost

    private void edatMascotaDretaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edatMascotaDretaFocusLost
        // TODO add your handling code here:
        try{
            confControl.getMascotaDreta().setEdat(Integer.valueOf(edatMascotaDreta.getText()));
        }catch(NumberFormatException ex){
            System.err.println("\t\t\t ERROR!! Edat Mascota Dreta invàlid !!!!");
        }     
    }//GEN-LAST:event_edatMascotaDretaFocusLost

    private void gatGosEsquerraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gatGosEsquerraFocusLost
        // TODO add your handling code here:
        confControl.getMascotaEsquerra().setGat((String)gatGosEsquerra.getSelectedItem());       
    }//GEN-LAST:event_gatGosEsquerraFocusLost

    private void gatGosDretaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gatGosDretaFocusLost
        // TODO add your handling code here:
        confControl.getMascotaDreta().setGat((String)gatGosDreta.getSelectedItem());
    }//GEN-LAST:event_gatGosDretaFocusLost

    private void botoValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoValidarActionPerformed
        // TODO add your handling code here:
        confControl.setejaLimitsDiaris();  
        dispose();
    }//GEN-LAST:event_botoValidarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Configuracio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Configuracio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Configuracio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Configuracio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Configuracio().setVisible(true);
            }
        });
    }
    //ACCESSORS
    public void setLimitDiariDretaText(JTextField limitDiariDretaText) {
        this.limitDiariDretaText = limitDiariDretaText;
    }

    public void setLimitDiariEsquerraText(JTextField limitDiariEsquerraText) {
        this.limitDiariEsquerraText = limitDiariEsquerraText;
    }

    public void setRaccionsDiariesDretaText(JTextField raccionsDiariesDretaText) {
        this.raccionsDiariesDretaText = raccionsDiariesDretaText;
    }

    public void setRaccionsDiariesEquerraText(JTextField raccionsDiariesEquerraText) {
        this.raccionsDiariesEquerraText = raccionsDiariesEquerraText;
    }

    public JTextField getLimitDiariDretaText() {
        return limitDiariDretaText;
    }

    public JTextField getLimitDiariEsquerraText() {
        return limitDiariEsquerraText;
    }

    public JTextField getNomMascotaDreta() {
        return nomMascotaDreta;
    }

    public JTextField getNomMascotaEsquerra() {
        return nomMascotaEsquerra;
    }

    public JTextField getPesMascotaDreta() {
        return pesMascotaDreta;
    }

    public JTextField getPesMascotaEsquerra() {
        return pesMascotaEsquerra;
    }

    public JTextField getRaccioExtraText() {
        return raccioExtraText;
    }

    public JTextField getRaccionsDiariesDretaText() {
        return raccionsDiariesDretaText;
    }

    public JTextField getRaccionsDiariesEquerraText() {
        return raccionsDiariesEquerraText;
    }
     
    public JTextField getEdatMascotaDreta() {
        return edatMascotaDreta;
    }

    public JLabel getFonsPantallaConfiguracio() {
        return fonsPantallaConfiguracio;
    }

    public JComboBox<String> getGatGosDreta() {
        return gatGosDreta;
    }

    public JComboBox<String> getGatGosEsquerra() {    
        return gatGosEsquerra;
    }

    public JTextField getAlertaDipositDretaText() {
        return alertaDipositDretaText;
    }

    public JTextField getAlertaDipositEsquerraText() {
        return alertaDipositEsquerraText;
    }

    public Controlador_Configuracio getConfControl() {
        return confControl;
    }

    public JTextField getEdatMascotaEsquerra() {
        return edatMascotaEsquerra;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alertaDipositDretaText;
    private javax.swing.JTextField alertaDipositEsquerraText;
    private javax.swing.JButton botoSortir;
    private javax.swing.JButton botoValidar;
    private javax.swing.JTextField edatMascotaDreta;
    private javax.swing.JTextField edatMascotaEsquerra;
    private javax.swing.JLabel fonsPantallaConfiguracio;
    private javax.swing.JComboBox<String> gatGosDreta;
    private javax.swing.JComboBox<String> gatGosEsquerra;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField limitDiariDretaText;
    private javax.swing.JTextField limitDiariEsquerraText;
    public javax.swing.JLabel limitNivellDipositBuitLabel;
    private javax.swing.JTextField nomMascotaDreta;
    private javax.swing.JTextField nomMascotaEsquerra;
    private javax.swing.JTextField pesMascotaDreta;
    private javax.swing.JTextField pesMascotaEsquerra;
    private javax.swing.JTextField raccioExtraText;
    private javax.swing.JTextField raccionsDiariesDretaText;
    private javax.swing.JTextField raccionsDiariesEquerraText;
    // End of variables declaration//GEN-END:variables


}


